# Generated by Django 5.2.5 on 2025-08-19 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
        ('postos', '0002_alter_posto_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='preco',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='posto_disponivel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='postos.posto'),
        ),
    ]
