# Generated by Django 5.2.5 on 2025-08-19 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0002_remove_medicamento_preco_and_more'),
        ('postos', '0002_alter_posto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='medicamentos/'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='posto_disponivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postos.posto'),
        ),
    ]
