# Generated by Django 5.2.5 on 2025-08-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0003_medicamento_foto_alter_medicamento_posto_disponivel'),
        ('postos', '0002_alter_posto_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='posto_disponivel',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='postos_disponiveis',
            field=models.ManyToManyField(related_name='medicamentos', to='postos.posto'),
        ),
    ]
