# Generated by Django 5.2.5 on 2025-08-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0004_remove_medicamento_posto_disponivel_and_more'),
        ('postos', '0002_alter_posto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='foto',
            field=models.ImageField(upload_to='medicamentos/'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='postos_disponiveis',
            field=models.ManyToManyField(blank=True, to='postos.posto'),
        ),
    ]
