# Generated by Django 5.2.5 on 2025-08-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='imagem_url',
        ),
        migrations.AddField(
            model_name='noticia',
            name='conteudo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/'),
        ),
    ]
