# Generated by Django 5.2.5 on 2025-08-19 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicamentos',
        ),
    ]
