# Generated by Django 5.1.6 on 2025-10-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='cartao_sus',
            new_name='num_cartao',
        ),
        migrations.AddField(
            model_name='reserva',
            name='cpf',
            field=models.CharField(default=0, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='foto_cartao',
            field=models.FileField(default=0, upload_to='cartoes/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='rg',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='telefone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
