# Generated by Django 5.1.6 on 2025-10-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_cartao_sus_reserva_num_cartao_reserva_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='quantidade',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
