# Generated by Django 5.1.6 on 2025-10-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_reserva_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='nome',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
