# Generated by Django 5.1.6 on 2025-10-07 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_admin', '0004_estoque'),
        ('home', '0006_reserva_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area_admin.estoque'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='posto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area_admin.postosaude'),
        ),
    ]
