# Generated by Django 5.1.6 on 2025-10-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_reserva_medicamento_alter_reserva_posto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITA', 'Aceita'), ('RECUSADA', 'Recusada'), ('RETIRADA', 'Retirada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=10),
        ),
    ]
