# Generated by Django 5.2.5 on 2025-08-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=20)),
                ('telefone1', models.CharField(max_length=20)),
                ('telefone2', models.CharField(blank=True, max_length=20, null=True)),
                ('horario_semana', models.CharField(max_length=50)),
                ('horario_sabado', models.CharField(max_length=50)),
                ('horario_domingo', models.CharField(max_length=50)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='postos/')),
            ],
        ),
    ]
