# Generated by Django 5.2.5 on 2025-08-19 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area_admin', '0002_posto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posto',
        ),
    ]
