# Generated by Django 5.1.6 on 2025-09-20 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_admin', '0003_delete_posto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id_medicamento', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='medicamentos/')),
                ('nome_medicamento', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('posto_saude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area_admin.postosaude')),
            ],
        ),
    ]
