# Generated by Django 5.1.6 on 2025-10-13 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_admin', '0004_estoque'),
        ('home', '0007_alter_reserva_medicamento_alter_reserva_posto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('data_mensagem', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.reserva')),
            ],
        ),
    ]
