# Generated by Django 5.1.6 on 2025-08-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='postos')),
                ('endereco', models.TextField()),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('telefone1', models.CharField(max_length=20)),
                ('telefone2', models.CharField(max_length=20)),
                ('horario_semana', models.CharField(max_length=100)),
                ('horario_sabado', models.CharField(max_length=100)),
                ('horario_domingo', models.CharField(max_length=100)),
            ],
        ),
    ]
