# Generated by Django 5.1.6 on 2025-08-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
    ]
