# Generated by Django 5.2.5 on 2025-09-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postos', '0002_alter_posto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='posto',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
